# Generated by Django 4.1 on 2024-05-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
