# Generated by Django 4.1 on 2024-05-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='uuid',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
