# Generated by Django 4.1 on 2024-05-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_course_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uuid',
            new_name='id',
        ),
    ]
