# Generated by Django 4.1 on 2024-05-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_uuid_course_id_rename_uuid_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
